### PR TITLE
Inital web framework of Keras-Contrib Website

### PR DESCRIPTION
**Pull request by Ankit-Dhankhar**
@ahundt This PR with reference to #220. This create Keras-contrib website (whose live demo is available at http://ankitdhankhar.me/keras-contrib/). Currently, for this website, some documentation of Keras is used. This PR will serve as foundation for coming PR related to documentation which will eventually used to build the website.

**PS:** I am currently working on some design issue on website.Like to know about the view of community on this and guidance how to proceed further.

Thanks & Regards,
Ankit

### CODE REVIEW

**Comment by ahundt** [comment]
Awesome, thanks for taking this on! I assume this is work in progress at the moment?

**Comment by anand-sonawane** [comment]
@Ankit-Dhankhar if you can give me access to your fork, I can start editing the files and structure of what you have created as per the keras-contrib repo. There are a lot things that have to removed and many more to be added, so we can work on that simultaneously on the same repo.

**Comment by Ankit-Dhankhar** [comment]
@anand-sonawane , Sure it would be great if you can help :)

**Comment by Ankit-Dhankhar** [comment]
@anand-sonawane , Sure it would be great if you can help :)

**Pull request closed without merging**
