### PR TITLE
[BatchRenorm] update running variance correctly

### PR DESCRIPTION
**Pull request by mrlzla**
Update moving running variance with batch running variance since it will work incorrect if we use large epsilon.

### CODE REVIEW

**Comment by titu1994** [comment]
Currently, the BatchRenorm implementation follows the paper closely. 

A large epsilon, (I am assuming closer to 1), is rarely every used in any normalization procedure. Perhaps only for demonstration purposes that they are equivalent under certain circumstances. 

Can you expand your case of why this change is necessary?

**Comment by mrlzla** [comment]
I pretty sure that is unnecessary, anyway there are some misunderstandings when update some metric related to variance with variable related to standart deviation.

**Comment by mrlzla** [comment]
After each minibatch we have got running_variance metric, which is greater than actual value by  eps * (1 - momentum). Let eps=1e-3, momentum=0.99. Then we have an error 1e-5. Through 1000 minibatches we have got an error that is greater than actual value by 1e-2, that is very big I think.

**Comment by titu1994** [comment]
Two things, can you demonstrate that this error affects training significantly, such that this fix is sufficient to correct. 

The error, if it exists, is not additive, and ann error of 1e-5 as you suggest may occur but it will be on a per batch basis, not add up to 1e-2 over all runs. 

Secondly, the source of the error in your opinion comes from the squaring of the standard deviation ? That error would be far smaller than the 1e-5 you suggest I think. 

In any case, I'm not averse to the change, but I want to make sure it doesn't reduce performance by mistake. If you could, please train a model with low batch sizes, and plot the loss graph. If it's similar to the plots in the discussion of the original inplementation of Batch Renorm, I'll merge it.

**Comment by mrlzla** [comment]
Unfortunately I have no enough free resources to train some model with batch renorm and this pull request only based on mathematical non-conformity. So I cannot say if it impoves results or not.

**Comment by titu1994** [comment]
Good analysis, but plugging in the values from your computation we find : 

> eps * (1 - momentum) as the error. 
> Xn_hat = Xn + err / (1 - momentum).

Xn_hat = Xn + (eps * (1-momentum)) / (1-momentum)

Therefore, Xn_hat = Xn + eps. I fail to see how you arrived at 1e-1 as your final error value. 

Since epsilon is normally 1e-3, the difference is small enough to be ignored.

**Comment by mrlzla** [comment]
Yes, my fault. 
1e-3 is really small enough. I have no arguments more :)

**Pull request closed without merging**
