### PR TITLE
Adding other codeowners.

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
**- What I did**
I added other codeowners.

**- How I did it**
I got them from itssue #415

**- How you can verify it**

The tests are passing.

### CODE REVIEW

**Comment by titu1994** [comment]
Could you add me to the list as discussed in PR #415 as well ?

**Comment by gabrieldemarmiesse** [comment]
Could you give the list of features? We discussed quite some things and I don't want to make a mistake.

**Comment by titu1994** [comment]
Sure. They are:

- all applications other than ResNet
- callbacks/snapshot: entire module
- layers/convolution: SubPixelUpscaling
- layers/normalization: GroupNormalization

**Comment by gabrieldemarmiesse** [comment]
Thanks! I'll split the convolution and normalization modules and then add you as the codeowner.

**Comment by titu1994** [comment]
Thanks !

**Pull request merged**
