### PR TITLE
Update resnet.py

### PR DESCRIPTION
**Pull request by SSchott**
https://github.com/keras-team/keras-contrib/issues/221
Explanation about input shape refers to dimensions and not channels?
Duplicated transition_dilation_rate

### CODE REVIEW

**Comment by christian-rauch** [comment]
@ahundt Would you consider merging this, or at least provide feedback?

**Comment by ahundt** [comment]
I don't see the motivation, dilation rates can have different dimensions. Isn't this change simply less functional? I haven't been using resnet recently because other models have outperformed it for my application.

**Comment by christian-rauch** [comment]
@ahundt any news on this? The ResNet model is virtually broken right now for larger ResNets. Can you please merge this or provide an example where this PR introduces an issue to existing models?

**Comment by ahundt** [comment]
Sure I can merge it. Sorry I have been under a rock for a while, I recently submitted my first paper a few weeks ago. :-)

**Pull request merged**
