### PR TITLE
Jaccard loss merge + example

### PR DESCRIPTION
**Pull request by ahundt**
pep8 fix plus example from #152, example + implementation credit @wassname, I just finished the last step in the review.

### CODE REVIEW

**Comment by ahundt** [comment]
This was already reviewed in #152, so if the unit tests pass I'll merge it.

**Comment by ahundt** [comment]
Updated to include minimum qualifying changes, pascal voc script will be saved for later.

**Comment by wassname** [comment]
Thanks!

**Comment by ahundt** [comment]
yay, it passes! merging

**Comment by wassname** [comment]
Nice! Thanks for that ahundt

**Pull request merged**
