### PR TITLE
wide_resnet.py keras 2 update

### PR DESCRIPTION
**Pull request by ahundt**

### CODE REVIEW

**Comment by titu1994** [comment]
I was wondering, shouldn't we replace the average pooling 8x8 by a GlobalAveragePooling2D? Its cleaner that way, and should continue to work properly. We can also remove the flatten then.

**Comment by ahundt** [comment]
I'm converting the code to work for segmentation problems as well, so in my case the change you describe would unfortunately be counterproductive.

**Comment by ahundt** [comment]
@titu1994 could you give this a quick review? I've been using it for a few weeks without issue now.

**Comment by titu1994** [comment]
You could add the pooling argument like the rest of the models and select what kind of pooling should occur. 

I think DenseNet implements this already so you could add it from there. Otherwise everything else is fine.

**Comment by ahundt** [comment]
switched to global average pooling as you suggested

**Comment by ahundt** [comment]
This change seems pretty trivial at this point and the error is unrelated, so I'll merge this.

**Pull request merged**
