### PR TITLE
Fix NASNet Weights

### PR DESCRIPTION
**Pull request by titu1994**
Implements the corrections in Keras master (https://github.com/keras-team/keras/pull/10209) to properly generate the model and load weights.

### CODE REVIEW

**Comment by titu1994** [comment]
@ahundt All tests failing for some reason.

**Comment by ahundt** [comment]
yeah there was a change in upstream keras we need to account for. I started fixing it in https://github.com/keras-team/keras-contrib/pull/256 but apparently the test needs to be updated too

**Comment by titu1994** [comment]
It is becoming a hassle to run tests against master Keras. Perhaps the partition of Keras into subcomponents will help with that.

**Comment by titu1994** [comment]
@ahundt Thanks for the review !

**Pull request merged**
